### ISSUE TITLE
[FEATURE] Make a onscreen timer of some sort for the recording part 

### ISSUE THREAD

**Issue by Trisanu-007** [Davidy22/SkunkBooth#73]
**Is your feature request related to a problem? Please describe.**
Once the recording button is clicked, start an onscreen timer with "REC"

**Describe the solution you'd like**
Simple state based implementation should do it.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by s-surineni** [comment]
Hi, Can I work on this feature?

**Comment by Trisanu-007** [comment]
Yeah sure, make sure to follow the guidelines and if you have any problems, don't hesitate to ask.

**Comment by s-surineni** [comment]
@Trisanu-007 I thought of changing the record checkbox to a timer. But asciimatics doesn't have a timer widget. 
Can you please suggest a way ahead? 
Should I use a label widget to `controls_layout` and update it according to the video duration?

**Comment by Davidy22** [comment]
Asciimatics has [this example](https://github.com/peterbrittain/asciimatics/blob/master/samples/top.py) with auto updating text that might be helpful for reference

**Comment by Trisanu-007** [comment]
@s-surineni check out David's reference and see if it would be a good fit. Also updating a custom widget does seem a good way too, but I cant speak for the performance. Do give it a try though.

**Comment by s-surineni** [comment]
@Trisanu-007 I've raised a PR to the issue. Please review and let me know if any changes are required. I did manual testing for the new code
