### ISSUE TITLE
Multiple Webcams

### ISSUE THREAD

**Issue by jJit0** [Davidy22/SkunkBooth#78]
**Is your feature request related to a problem? Please describe.**

I have 2 webcams on my thinkpad, first is IR-Camera and the second one is a classic webcam.
Here is the output of /dev: /dev/video0  /dev/video1  /dev/video2  /dev/video3
The issue here is I can't change cameras in SkunkBooth, and by default it opens the IR-Camera which is /dev/video2

Is there a way to change it ?

**Comment by Davidy22** [comment]
There's no webcam detection/selection yet, currently just grabs the first one found, but if someone's up for it extra webcam detection's a welcome addition.

**Comment by jJit0** [comment]
Oh okay…

In that case, is there a way to change it manually, like modifying a piece of code kn the script?

**Comment by Davidy22** [comment]
if you just want to change a number, [this line](https://github.com/Davidy22/SkunkBooth/blob/c4510832dfefd54b10f0435f24c72c6191e79392/skunkbooth/utils/CamReader.py#L21) is the one that selects the camera. Change the number from 0 to 1 or 2 and experimentally find the number of your webcam. If you're up for it, we also very much welcome patches if you're interested in writing a more general implementation of this feature

**Comment by jJit0** [comment]
Great thank you.

It worked for me, I changed 0 to 2. All good

**Comment by Davidy22** [comment]
If you're willing, we welcome patches if you want to write some camera detection and switching in the options
