### ISSUE TITLE
[MISC] HacktoberFest 

### ISSUE THREAD

**Issue by Trisanu-007** [Davidy22/SkunkBooth#79]
@Davidy22 if you want, we could open this repo for HacktoberFest. Here are the guidelines : https://hacktoberfest.digitalocean.com/. I think it requires you to change the labels for the repo, rest all is done.

**Comment by Davidy22** [comment]
Yeah sure, marked a few things that could be appropriate for it.

**Comment by Davidy22** [comment]
Oh actually read through a bit more, the good for newcomers tag is enough probably
