### ISSUE TITLE
[MISC] Minor Update to README.md for Cloning Instructions

### ISSUE THREAD

**Issue by brilam** [Davidy22/SkunkBooth#80]
## Describe the issue :
While this isn't really a big issue, I noticed that the clone instructions mentions to clone the repo 'scholarlySkunkJam' and cd into the folder. Considering how the repo has been renamed to SkunkBooth and all other instructions mentions SkunkBooth, I think this should be changed in the README for consistency purposes.

## Solution, if any :
1. Update the README as mentioned above.

**Comment by Davidy22** [comment]
Thanks for the notice, missed that during the move. PR merged, so closing.
