### ISSUE TITLE
[FEATURE] New fitler: grayscale

### ISSUE THREAD

**Issue by codephile1221** [Davidy22/SkunkBooth#91]
After reading issue #69, I felt it would be nice to have a grayscale filter- because grayscale images are minimalistic and is a pretty standard filter.
I haven't looked into the implementation but I guess it should be simple enough.
It would be appreciated if this issue could be assigned to me.

**Comment by Davidy22** [comment]
If you want to write it you can just go ahead and make the PR and I'll check it to make sure it works.
